name: Sync Calendar
on:
  schedule:
    - cron: '0 * * * *' # This runs every hour
  workflow_dispatch: # This allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Calendar
        run: curl -L "${{ secrets.CALENDAR_URL }}" -o calendar.ics

      - name: Commit and Push
        run: |
          git config --global user.name 'Calendar Bot'
          git config --global user.email 'bot@github.com'
          git add calendar.ics
          git commit -m "Update calendar" || exit 0
          git push
